config/routes.rb
Rails.application.routes.draw do

  resources :item_pedidos
  resources :usuarios, only: [:new, :create]
  resources :restaurantes
  resource :confirmation, only: [:show]
  resource :user_sessions, only: [:create, :new, :destroy]
  get '/login' => 'user_sessions#new'
  get '/entrar' => 'user_sessions#new'
  get '/pedidos/checkout' => 'pedidos#checkout' # quando o cliente clica em finalizar, na tela do restaurante
  get '/pedidos/acompanhamento' => 'pedidos#acompanhamento'
  resources :pedidos, only: [:create, :new, :destroy, :show, :update]
  get '/account' => 'account#index'

  get '/painel' => 'painel#index'
  get '/painel/pedidos' => 'painel#pedidos'
  get 'painel/pedidos/:id' => 'painel#show_pedido'
  post '/painel/pedidos/' => 'painel#encerrar_pedido'
  post '/painel/cancelar_pedido/' => 'painel#cancelar_pedido'
  get '/painel/produtos' => 'painel#produtos'
  get '/painel/produtos/new' => 'itens#new'
  get '/painel/restaurante' => 'painel#restaurante'
  get 'painel/pizzas' => 'painel#pizzas'
  get 'painel/pizzas/new' => 'painel#new_sabor'
  get 'painel/edit_sabor/:id' => 'painel#edit_sabor'
  post 'painel/pizzas/new' => 'painel#create_sabor'
  patch 'painel/edit_sabor/update/:id' => 'painel#update_sabor'
  post 'painel/pizzas/:id' => 'painel#destroy_sabor'

  resources :enderecos, only: [:create, :new, :destroy]
  resources :itens
  get '/contato' => 'home#suporte'
  get '/cadastro_restaurante' => 'home#cadastro_restaurante'
  get 'precadastro' => 'home#cadastro_restaurante'
  post '/cadastro_restaurante' => 'home#precadastro'
  get 'cadastro_restaurante/sucesso' => 'home#precadastro_sucesso'

  get 'dashboard' => 'dashboard#index'
  get 'dashboard/pedidos' => 'dashboard#pedidos'
  get 'dashboard/pedidos/:id' => 'dashboard#show_pedido'
  get 'dashboard/precadastro' => 'dashboard#precadastro'
  get 'dashboard/edit/:id' => 'dashboard#edit'
  post 'dashboard/update/:id'=> 'dashboard#update'
  patch 'dashboard/update/:id'=> 'dashboard#update'

  get '/busca_restaurantes' => 'restaurantes#busca'

  root 'home#index'

end

app/models/restaurante.rb
class Restaurante < ActiveRecord::Base
	belongs_to :usuario
	belongs_to :cozinha
	has_one :endereco
	has_many :itens
	has_many :pizza_restaurantes
	has_many :pedidos
	has_many :sabores_de_pizza
	validates_associated :usuario, :cozinha
	validates_presence_of :usuario_id

	mount_uploader :imagem, ImagemUploader
end

app/controllers/restaurantes_controller.rb
class RestaurantesController < ApplicationController
	include CurrentPedido
	include TimeOperations

	before_action :require_authentication, only: [:new, :edit, :create, :update, :destroy]
	before_action :store_return_to
	before_action :get_pedido, only: [:show, :edit, :update, :destroy]

	def index
      #Lista somente restaurantes ativos
		@restaurantes = Restaurante.where(status: 'ATIVO')
	end

	def busca

	end

	def show
		@restaurante = Restaurante.find(params[:id])
		@cardapio = Item.where(restaurante_id: params[:id]).order(:categoria_id)
		@categorias = Categoria.all
		@pedido_iniciado_neste_restaurante = if !@pedido.nil? && @pedido.restaurante.try(:id) == @restaurante.id
			true
		else
			false
		end
		#@aberto = aberto?
		@hora_agora = date_to_time(Time.now)
		@pedido_minimo = @restaurante.pedido_minimo_centavos
	end



	def new
		if current_user.restaurante
			@restaurante = current_user.restaurante
			redirect_to @restaurante, notice: 'Você já tem um restaurante.'
		end
		@restaurante = Restaurante.new
		@cozinhas = Cozinha.all
	end

	def edit
		@restaurante = current_user.restaurante
	end
	def update
		@restaurante = current_user.restaurante
		if @restaurante.update(restaurante_params)
			redirect_to painel_path, notice: "Dados do restaurante atualizados com sucesso!"
		else
			render action: "edit"
		end
	end

	def create


		@restaurante = current_user.build_restaurante(restaurante_params)

		if @restaurante.save
			redirect_to painel_path, notice: t('flash.notice.restaurante_created')
		else
			redirect_to new_restaurante_path, notice: "Não deu certo :("
		end
	end

	def destroy
		@restaurante = current_user.restaurantes.find(params[:id])
		@restaurante.destroy

		redirect_to restautantes_url
	end

	private

	def restaurante_params
		params.require(:restaurante).permit(:nome, :descricao, :cozinha_id, :pedido_minimo_centavos, :hora_inicio, :hora_fim, :imagem, :metodo_pagamento)
	end

	def aberto?
		@restaurante = Restaurante.find(params[:id])

		if time_to_minutos(Time.now) > time_to_minutos(@restaurante.hora_fim)
			false
		else
			true
		end

	end
end

app/views/restaurantes/_form.html.erb
<%= form_for @restaurante, html: {class: "form-horizontal", role: "form"} do |f|%>
			<div class="form-group">

				<%= f.label :imagem, "Imagem do restaurante", class: "col-sm-3 control-label" %>
				<div class="col-sm-9">
					<%= f.file_field :imagem, class: 'form-control', placeholder: "Imagem do restaurante" %>
					<span id="helpBlock" class="help-block">Deve ser quadrada, 200 x 200 pixels</span>

				</div>

			</div>
			<div class="form-group">

				<%= f.label :nome, t('.nome'), class: "col-sm-3 control-label" %>
				<div class="col-sm-9">
					<%= f.text_field :nome, class: 'form-control', placeholder: "Nome do restaurante" %>
				</div>

			</div>

         <div class="form-group">

            <%= f.label :metodo_pagamento, "Formas de pagamento", class: "col-sm-3 control-label" %>
            <div class="col-sm-9">

               <select class="form-control" name="restaurante[metodo_pagamento]" id="restaurante_metodo_pagamento">

					<%= options_for_select([
                  ['Dinheiro e cartões (créd/deb)', 'Dinheiro e cartões (créd/deb)'],
                  ['Dinheiro e cartão de débito','Dinheiro e cartão de débito'], ['Dinheiro', 'Dinheiro']]) %>

               </select>


            </div>

         </div>
         
			<div class="form-group">

				<%= f.label :cozinha_id, "Cozinha", class: "col-sm-3 control-label" %>
				<div class="col-sm-9">
					<select class="form-control" name="restaurante[cozinha_id]" id="restaurante_cozinha_id">
					<%= options_from_collection_for_select(@cozinhas, :id, :nome) %>
				</select>

				</div>

			</div>

			<div class="form-group">

				<%= f.label :descricao, t('.descricao'), class: "col-sm-3 control-label" %>
				<div class="col-sm-9">
					<%= f.text_area :descricao, class: 'form-control', placeholder: "Descrição do restaurante" %>
					<span id="helpBlock" class="help-block">Descrição completa do restaurante. Essa descrição vai aparecer na listagem de restaurantes e na página individual do restaurante.</span>

				</div>

			</div>



			<div class="form-group">

				<%= f.label :pedido_minimo_centavos, "Pedido mínimo", class: "col-sm-3 control-label" %>
				<div class="col-sm-9">
					<%= f.text_field :pedido_minimo_centavos, class: 'form-control', placeholder: "Digite apenas números, os dois últimos dígitos são centavos." %>
					<span id="helpBlock" class="help-block">Digite apenas números, os dois últimos dígitos são centavos. Ex: 2075 (R$ 20,75)</span>
				</div>

			</div>

			<div class="form-group">

				<%= f.label :hora_inicio, "Hora de abertura", :ignore_date => true, class: "col-sm-3 control-label" %>
				<div class="col-sm-9">
					<%= f.time_select :hora_inicio, class: 'form-control', placeholder: "Hora de abertura" %>
					<span id="helpBlock" class="help-block">Hora em que o restaurante abre</span>

				</div>

			</div>

			<div class="form-group">

				<%= f.label :hora_fim, "Hora de fechamento", :ignore_date => true, class: "col-sm-3 control-label" %>
				<div class="col-sm-9">
					<%= f.time_select :hora_fim, class: 'form-control', placeholder: "Hora de fechamento" %>
					<span id="helpBlock" class="help-block">Hora em que o restaurante fecha</span>

				</div>

			</div>


			<div class="form-group">

				<div class="col-sm-3"></div>
				<div class="col-sm-9">

					<%= f.button t('.submit'), class: 'btn btn-primary' %>

			    </div>
			</div>

		<%end%>

app/views/restaurantes/busca.html.erb
<% content_for :title do %> Restaurantes | Comidelivery - Delivery Online | Faça seu pedido <% end %>
<% flash.each do |name, msg| -%>
	<%= content_tag :div, msg, class: "alert alert-success" %>
<% end -%>

<h1>Restaurantes</h1>

<div class="row">
	<div class="col-md-8">



		<p>Nenhum restaurante encontrado perto de você.</p>



	</div>

</div>

app/views/restaurantes/index.html.erb
<% content_for :title do %> Restaurantes | Comidelivery - Delivery Online | Faça seu pedido <% end %>
<% flash.each do |name, msg| -%>
	<%= content_tag :div, msg, class: "alert alert-success" %>
<% end -%>

<h1>Restaurantes</h1>	

<div class="row">
	<div class="col-md-8">

		

		<% @restaurantes.each do |restaurante|  %>

		
		<div class="col-sm-6 col-md-4">
		    <div class="thumbnail lista-restaurantes-item">
		      <img src="<%= restaurante.imagem.url %>" alt="<%= restaurante.nome %>">
		      <div class="caption">
		        <h4><%= restaurante.nome %></h4>
		        <p class="cozinha">Cozinha: <%= restaurante.cozinha.nome %></p>
		        <p class="descricao"><%= truncate(restaurante.descricao, length: 70) %></p>
		        <p><a href="/restaurantes/<%= restaurante.id %>-<%= restaurante.nome.parameterize%>" class="btn btn-primary btn-block" role="button">Ver cardápio</a>
		      </div>
		    </div>
  		</div>

		<% end %>

		

	</div>

</div>

app/views/restaurantes/new.html.erb
<% content_for :title do %>Cadastro de Restaurante | Comidelivery.com <% end %>
<div class="row">
	<div class="col-md-6">
<div class="page-header">
	<h1><%= t ".title" %></h1>
</div>

<% flash.each do |name, msg| -%>
	<%= content_tag :div, msg, class: "alert alert-success" %>
<% end -%>

<%= render 'form' %>
	</div><!-- col -->
</div><!-- row -->

app/views/restaurantes/show.html.erb
<% content_for :title do %> <%= @restaurante.nome %> | Comidelivery - Delivery Online | Faça seu pedido <% end %>
<% flash.each do |name, msg| -%>
	<%= content_tag :div, msg, class: "alert alert-success" %>
<% end -%>

<div class="row">
	<div class="col-md-9"><!-- Cardápio -->

		<div class="cabecalho"><!-- cabecalho -->
			<img class="show-restaurante-img"src="<%= @restaurante.imagem.url %>" alt="<%= @restaurante.nome %>">
			<h1><%= @restaurante.nome %><small>(<%= @restaurante.cozinha.nome %>)</small></h1>
			<div class="panel panel-default">
			  <div class="panel-body">
             <small></small>
			    <p class="restaurante-descricao"><%= @restaurante.descricao %></p>
			  </div>
			  <div class="panel-footer detalhes-do-restaurante">
             <small>

			  	<span class="restaurante-hora-abre"><strong>Funcionamento: </strong><%= date_to_time(@restaurante.try(:hora_inicio)) %> até <%= date_to_time(@restaurante.try(:hora_fim))%></span>

            <span><strong>Pedido mínimo: </strong>R$ <%= centavos_em_real(@restaurante.pedido_minimo_centavos) %></span>


            <span class="restaurante-metodo-pagamento"><strong>Pagamento: </strong><%= @restaurante.try(:metodo_pagamento) %></span>

         </small>


			  </div>
			</div>

		</div><!-- /cabecalho -->






<h2>Cardápio</h2>


<div class="row"> <!-- lista de produtos -->
	<div class="col-md-12">


<% # inicio categoria. Solução que carece elegância para exibir titulo somente da categoria que existir no cardápio %>

<% @categorias.each do |categoria| %>

<% tem_categoria = false%>

<% @cardapio.each do |i| %>
	<% if (i.categoria == categoria) then tem_categoria = true %>
	<% end %>
<% end %>


	<% if tem_categoria %>
		<h3 class="categoria-heading"><%= categoria.nome %></h3>
	<% end %>
<% #end %>

<% @cardapio.each do |item| %>

<% if item.categoria == categoria %>



<table class="table table-cardapio">


	<tr>

		<td class="td-nome">
			<p><strong><%= item.nome %></strong><p>
			<p><%= item.descricao %></p>
		</td>

		<td class="td-preco"><strong><%= currency_symbol %> <%= centavos_em_real(item.preco_centavos) %></strong></td>



		<td class="td-adicionar">
         <% if (@restaurante.status == 'ATIVO') then #exibe o pedido somente se o usuário estiver ativo %>

			<% unless @pedido.nil? then %>

				<% unless @pedido_iniciado_neste_restaurante then %>

				<%= button_to 'Adicionar ao Pedido', item_pedidos_path(item_id: item),disabled: "disabled" ,class: "btn btn-primary", remote: true  %>

				<% else %>

				<%= button_to 'Adicionar ao Pedido', item_pedidos_path(item_id: item), class: "btn btn-primary", remote: true  %>

				<% end %>

			<% else %>

				<%= button_to 'Adicionar ao Pedido', item_pedidos_path(item_id: item), class: "btn btn-primary", remote: true  %>

			<% end %>

         <% end #fim condicional de STATUS%>




		</td>

	</tr>




</table>
<% end #loop produtos %>

<% end #if %>

<% end # loop categorias%>

<% # fim categoria %>

</div><!-- col lista de produtos -->
</div><!-- fim lista de produtos-->

</div><!-- col-md-9 cardapio -->

<% if (@restaurante.status == 'ATIVO') then #exibe o pedido somente se o usuário estiver ativo %>

<div class="col-md-3 pedido-sidebar" id="pedido">

	<% unless @pedido.nil? %>

		<% unless @pedido_iniciado_neste_restaurante then %>

		<h2>Seu pedido</h2>
		<p class="bg-warning text-warning">Atenção, você começou um pedido em outro restaurante. Finalize o pedido antes de fazer outro ou clique no botão abaixo para esvaziar seu pedido e continuar em outro restaurante.</p>

		<%= button_to 'Esvaziar pedido', @pedido, method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-sm btn-danger'%>

		<% else %>

			<%= render @pedido %>

		<% end %>

	<% else %>

	<h2>Seu pedido</h2>

	<p>Seu pedido está vazio</p>

	<% end %>


</div> <!-- Pedido sidebar -->

<% end #fim da condicional de STATUS do restaurante%>



</div><!-- row -->