config/routes.rb
Rails.application.routes.draw do

  resources :item_pedidos
  resources :usuarios, only: [:new, :create]
  resources :restaurantes
  resource :confirmation, only: [:show]
  resource :user_sessions, only: [:create, :new, :destroy]
  get '/login' => 'user_sessions#new'
  get '/entrar' => 'user_sessions#new'
  get '/pedidos/checkout' => 'pedidos#checkout' # quando o cliente clica em finalizar, na tela do restaurante
  get '/pedidos/acompanhamento' => 'pedidos#acompanhamento'
  resources :pedidos, only: [:create, :new, :destroy, :show, :update]
  get '/account' => 'account#index'

  get '/painel' => 'painel#index'
  get '/painel/pedidos' => 'painel#pedidos'
  get 'painel/pedidos/:id' => 'painel#show_pedido'
  post '/painel/pedidos/' => 'painel#encerrar_pedido'
  post '/painel/cancelar_pedido/' => 'painel#cancelar_pedido'
  get '/painel/produtos' => 'painel#produtos'
  get '/painel/produtos/new' => 'itens#new'
  get '/painel/restaurante' => 'painel#restaurante'
  get 'painel/pizzas' => 'painel#pizzas'
  get 'painel/pizzas/new' => 'painel#new_sabor'
  get 'painel/edit_sabor/:id' => 'painel#edit_sabor'
  post 'painel/pizzas/new' => 'painel#create_sabor'
  patch 'painel/edit_sabor/update/:id' => 'painel#update_sabor'
  post 'painel/pizzas/:id' => 'painel#destroy_sabor'

  resources :enderecos, only: [:create, :new, :destroy]
  resources :itens
  get '/contato' => 'home#suporte'
  get '/cadastro_restaurante' => 'home#cadastro_restaurante'
  get 'precadastro' => 'home#cadastro_restaurante'
  post '/cadastro_restaurante' => 'home#precadastro'
  get 'cadastro_restaurante/sucesso' => 'home#precadastro_sucesso'

  get 'dashboard' => 'dashboard#index'
  get 'dashboard/pedidos' => 'dashboard#pedidos'
  get 'dashboard/pedidos/:id' => 'dashboard#show_pedido'
  get 'dashboard/precadastro' => 'dashboard#precadastro'
  get 'dashboard/edit/:id' => 'dashboard#edit'
  post 'dashboard/update/:id'=> 'dashboard#update'
  patch 'dashboard/update/:id'=> 'dashboard#update'

  get '/busca_restaurantes' => 'restaurantes#busca'

  root 'home#index'

end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
	belongs_to :usuario
	belongs_to :restaurante
	belongs_to :endereco
	belongs_to :metodo
	has_many :itens, through: :item_pedidos
	has_many :item_pedidos
	has_many :pizza_pedidos
	validates_associated :usuario, :restaurante, :endereco, :metodo

	def add_item (item_id)
	current_item = item_pedidos.find_by(item_id: item_id)			
		
		if current_item
			current_item.quantidade += 1
		else
			current_item = item_pedidos.build(item_id: item_id)				
		end
		current_item
	end

	def preco_total
		item_pedidos.to_a.sum { |item| item.preco_total }		
	end


end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
	include CurrentPedido

	before_action :set_pedido, only: [:show, :edit, :update, :destroy, :checkout]
	before_action :require_authentication, only: [:checkout, :acompanhamento, :update]
	before_action :store_return_to
	rescue_from ActiveRecord::RecordNotFound, with: :pedido_invalido

	def new
		@pedido = Pedido.new
	end

	def create #guardar para a finalização do pedido

	end

	def show
	end

	def checkout # Primeiro botão Finalizar, ainda na tela do restaurante. Os pedidos costumam não ter dono em nosso BD
		@pedido.status = 2
		@usuario = current_user
	end

	def acompanhamento
		@pedidos = current_user.pedidos.where("status > 1").order(id: :desc)

		if @pedidos.empty?
			redirect_to account_path, notice: "Você precisa finalizar seu pedido para acompanhá-lo."
		end

		@usuario = current_user
	end

	def update #quando o cliente clica em Finalizar Pedido, na tela de checkout

		@pedido.status = 3 #altera status para 'finalizado'

		@pedido.usuario_id = current_user.id #atribui um usuário. Nesta fase, o login é obrigatório

		@pedido.send_at = Time.now #atualiza a hora do despacho do pedido. Quando houver pagamento, esta hora deverá ser a mesma da confirmação de pagamento


		if @pedido.update(checkout_params)#se tudo der certo...
         #dispara e-mail para o cliente, o restaurante e para nós mesmos
         UserNotifier.send_novo_pedido_email(@pedido).deliver


			session[:pedido_id] = nil #apaga o 'carrinho de compras do pedido salvo em cache no navegador do cliente'
			redirect_to pedidos_acompanhamento_path, notice: "Pedido finalizado com sucesso"

		else
			render pedido_checkout_path
		end
	end

	def destroy
		@pedido.destroy if @pedido.id == session[:pedido_id] and session[:pedido_id] != nil
		session[:pedido_id] == nil
		respond_to do |format|
			format.html { redirect_to restaurantes_url, notice: 'Seu pedido está vazio'}
			format.json { head :no_content }
		end

	end

	private

    # Never trust parameters from the scary internet, only allow the white list through.
    def pedido_params
      params[:pedido]
    end

    def checkout_params
    	params.require(:pedido)
		.permit(:endereco_id, :id_forma_pagamento, :comentario)

    end

	def pedido_invalido
		logger.error "Tentativa de acesso invalido ao pedido #{params[:id]}"
		redirect_to restaurantes_url, notice: "Pedido inválido"
	end

end

app/views/pedidos/_item_pedido.html.erb
<li class="list-group-item"><%= item_pedido.quantidade %> x <%= item_pedido.item.nome %> - <%= centavos_em_real(item_pedido.preco_total) %>
	<%= button_to 'Remover', item_pedido, method: :delete, class: "btn btn-danger btn-xs" %>
</li>

app/views/pedidos/_item_pedido_checkout.html.erb
<li><%= item_pedido.quantidade %> x <%= item_pedido.item.nome %> - <%= centavos_em_real(item_pedido.preco_total) %>
	<%= button_to 'Remover', item_pedido, method: :delete, class: "btn btn-danger btn-xs" %>
</li>

app/views/pedidos/_pedido.html.erb
<h2>Seu Pedido</h2>

<%if pedido.item_pedidos.empty? %>
<p>Seu pedido está vazio.</p>	
<% else %>
<%= render(pedido.item_pedidos) %>
<p></p>
<%= button_to 'Esvaziar pedido', pedido, method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-sm btn-danger'%>

<div class="row"><!-- ********* subtotal ******** -->
		<div class="col-md-7">
			<p><strong>Subtotal</strong></p>
		</div>
		<div class="col-md-5">
			<p class="">
				<strong><%= currency_symbol %> <%= centavos_em_real(pedido.preco_total) %></strong>
			</p>
		</div>

	</div><!-- /subtotal -->

	<%= link_to "Finalizar pedido", pedidos_checkout_path, class: "btn btn-lg btn-success btn-block" %>

	<% end %>

app/views/pedidos/acompanhamento.html.erb
<% content_for :title do %> Acompanhamento | Comidelivery - Delivery Online<% end %>
<% flash.each do |name, msg| -%>
	<%= content_tag :div, msg, class: "alert alert-success" %>
<% end -%>

<div class="row">
	<div class="col-md-6">
<h2>Acompanhe seu pedido</h2>
<hr>

</div><!-- row -->
</div><!-- col -->



	<% @pedidos.each do |pedido| %>

	<div class="row">

	<div class="col-md-6">



		<div class="panel panel-default">

		  <div class="panel-heading">
		    <h3 class="panel-title"><strong><%= pedido.restaurante.try(:nome) %> <%= Time.zone.at(pedido.updated_at).strftime("%d/%m/%Y - %H:%M") %> (ID: <%= pedido.id %>)</strong></h3>
		  </div>


		<div class="panel-body">

		  	<strong>Itens:</strong>
		</div>



		<!-- List group -->
		<ul class="list-group">

			<% pedido.item_pedidos.each do |itempedido| %>
			<li class="list-group-item"><%= itempedido.quantidade%> x <%= itempedido.item.nome %> - <%= currency_symbol %> <%= centavos_em_real(itempedido.item.preco_centavos) %></li>
			<% end %>

			<li class="list-group-item"><strong>Total: <%= currency_symbol %> <%= centavos_em_real(pedido.preco_total) %></strong></li>

			<li class="list-group-item"><strong>Saiu para entrega?</strong>
				<% if pedido.status == 4 %>
				Sim
				<% else %>
				Não
				<% end %>
			</li>


		</ul><!-- list group-->

		</div>
	</div><!-- col -->
	</div><!-- pedidos row -->



		<% end %>

app/views/pedidos/checkout.html.erb
<% content_for :title do %> Checkout | Comidelivery - Delivery Online<% end %>

<% flash.each do |name, msg| -%>
	<%= content_tag :div, msg, class: "alert alert-success" %>
<% end -%>

<div class="row">
	<div class="col-md-6">
<h2>Checkout<small> | Finalize seu pedido</small></h2>

<%if @pedido.item_pedidos.empty? %>
<p>Seu pedido está vazio.</p>	
<% else %>


<h3>1 - Confira seu pedido</h3>
<ul class="list-group">

<%= render(@pedido.item_pedidos) %>


<li class="list-group-item"><h4><strong>Subtotal: <%= currency_symbol %> <%= centavos_em_real(@pedido.preco_total) %></strong> <small>Forma de pagamento: na entrega.</small></h4></li>

</ul>

</div><!-- col -->
</div><!-- row-->



<div class="row">
<div class="col-md-6">
	<h3>2 - Endereço de entrega</h3>

	<%= form_for @pedido, html: {class: "form-horizontal", role: "form"} do |f| %>

	<div class="form-group">

        <%= f.label :endereco_id, "Endereço", class: "col-sm-2 control-label" %>
        <div class="col-sm-6">
          <select class="form-control" name="pedido[endereco_id]" id="endereco_id">
          <%= options_from_collection_for_select(@usuario.enderecos, :id, :nome) %>
        </select>
          
        </div>
        <div class="col-md-4"><%= link_to 'Novo endereço', new_endereco_path, class: "btn btn-success" %></div>
        
        
  	</div>
    </div><!-- row-->
</div>  <!-- col -->

<div class="row">
  <div class="col-md-6">


    <h3>3 - Comentário</h3>

    <div class="form-group">

      <%= f.label :comentario, "Comentáio", class: "col-sm-2 control-label" %>
      <div col="col-sm-6">

        <span id="helpBlock" class="help-block">Use este espaço para solicitações diversas. Por exemplo, retirar um ingrediente.</span>
        <%= f.text_field :comentario, class: 'form-control', placeholder: "Comentário" %>


      </div>

    </div>

<%= submit_tag 'Finalizar pedido', class:"btn btn-lg btn-success" %>
<p></p>

<% end %><!-- end form_for -->

</div><!-- row-->
</div>	<!-- col -->





<% end %>

app/views/pedidos/show.html.erb
<% flash.each do |name, msg| -%>
	<%= content_tag :div, msg, class: "alert alert-success" %>
<% end -%>

<%= render @pedido %>