config/routes.rb
Rails.application.routes.draw do

  resources :item_pedidos
  resources :usuarios, only: [:new, :create]
  resources :restaurantes
  resource :confirmation, only: [:show]
  resource :user_sessions, only: [:create, :new, :destroy]
  get '/login' => 'user_sessions#new'
  get '/entrar' => 'user_sessions#new'
  get '/pedidos/checkout' => 'pedidos#checkout' # quando o cliente clica em finalizar, na tela do restaurante
  get '/pedidos/acompanhamento' => 'pedidos#acompanhamento'
  resources :pedidos, only: [:create, :new, :destroy, :show, :update]
  get '/account' => 'account#index'

  get '/painel' => 'painel#index'
  get '/painel/pedidos' => 'painel#pedidos'
  get 'painel/pedidos/:id' => 'painel#show_pedido'
  post '/painel/pedidos/' => 'painel#encerrar_pedido'
  post '/painel/cancelar_pedido/' => 'painel#cancelar_pedido'
  get '/painel/produtos' => 'painel#produtos'
  get '/painel/produtos/new' => 'itens#new'
  get '/painel/restaurante' => 'painel#restaurante'
  get 'painel/pizzas' => 'painel#pizzas'
  get 'painel/pizzas/new' => 'painel#new_sabor'
  get 'painel/edit_sabor/:id' => 'painel#edit_sabor'
  post 'painel/pizzas/new' => 'painel#create_sabor'
  patch 'painel/edit_sabor/update/:id' => 'painel#update_sabor'
  post 'painel/pizzas/:id' => 'painel#destroy_sabor'

  resources :enderecos, only: [:create, :new, :destroy]
  resources :itens
  get '/contato' => 'home#suporte'
  get '/cadastro_restaurante' => 'home#cadastro_restaurante'
  get 'precadastro' => 'home#cadastro_restaurante'
  post '/cadastro_restaurante' => 'home#precadastro'
  get 'cadastro_restaurante/sucesso' => 'home#precadastro_sucesso'

  get 'dashboard' => 'dashboard#index'
  get 'dashboard/pedidos' => 'dashboard#pedidos'
  get 'dashboard/pedidos/:id' => 'dashboard#show_pedido'
  get 'dashboard/precadastro' => 'dashboard#precadastro'
  get 'dashboard/edit/:id' => 'dashboard#edit'
  post 'dashboard/update/:id'=> 'dashboard#update'
  patch 'dashboard/update/:id'=> 'dashboard#update'

  get '/busca_restaurantes' => 'restaurantes#busca'

  root 'home#index'

end

app/controllers/painel_controller.rb
class PainelController < ApplicationController
	before_action :require_authentication, :require_have_restaurant
	before_action :store_return_to
	before_action :get_usuario
	before_action :get_restaurante
	before_action :get_pedidos
	before_action :get_qtde_pedidos_abertos

	###
	# Ciclo do pedido
	# 0 - Default
	# 1 -
	#
	###

	def index
	redirect_to painel_pedidos_path
	end

	def pedidos
		@vendas = @pedidos.to_a.sum { |item| item.preco_total }
	end

	def produtos
		@produtos = Item.where(restaurante_id: @restaurante.id).order(:categoria_id)
	end

	def pizzas #mostra os SABORES de pizza do restaurante
		@sabores = SaboresDePizza.where(restaurante_id: @restaurante.id)
	end

	def new_sabor #cria um novo SaborDePizza
		@sabor = SaboresDePizza.new
	end

	def create_sabor

		@sabor = SaboresDePizza.new(sabor_params)
		@sabor.restaurante_id = current_user.restaurante.id



		respond_to do |format|
	    	if @sabor.save(sabor_params)
	        	format.html { redirect_to painel_pizzas_path, notice: "Sabor de pizza criada com sucesso."}
	        	format.json { render :show, status: :created, location:  item_path }
	      	else
	        	format.html { render :new }
	        	format.json { render json: @pizza.errors, status: :unprocessable_entity }
	      	end
  		end
	end

	def edit_sabor
		@sabor = SaboresDePizza.find(params[:id])
	end

	def update_sabor
		@sabor = SaboresDePizza.find(params[:id])

		if @sabor.update(sabor_params)
			redirect_to painel_pizzas_path, notice: "Pizza atualizada com sucesso"
		else
			render action: "edit_sabor"
		end
	end

	def destroy_sabor
		@sabor = SaboresDePizza.find(params[:id])

		@sabor.destroy

    	respond_to do |format|
      		format.html { redirect_to painel_pizzas_path, notice: 'Pizza excluida com sucesso.' }
      		format.json { head :no_content }
      	end
	end

	def show_pedido
		@pedido = @pedidos.find(params[:id])
	end

	def encerrar_pedido #ultima ação caso ocorra tudo bem.
		@pedido = Pedido.find(params[:pedido_id])
		@pedido.status = 4 #codigo de pedido encerrado

		if @pedido.save
         UserNotifier.send_pedido_encerrado_email(@pedido).deliver
			redirect_to painel_pedidos_path, notice: "Pedido encerrado com sucesso. O cliente será notificado de que seu pedido saiu para entrega."
		else
			redirect_to painel_pedidos_path, notice: "Ops. Ocorreu algum erro. Tente encerrar o pedido novamente."
		end
	end

   def cancelar_pedido
		@pedido = Pedido.find(params[:pedido_id])
		@pedido.status = 5 #codigo de pedido cancelado pelo restaurante SEM ENTREGA AO CLIENTE

		if @pedido.save

         UserNotifier.send_pedido_cancelado_email(@pedido).deliver

			redirect_to painel_pedidos_path, notice: "Pedido cancelado com sucesso."
		else
			redirect_to painel_pedidos_path, notice: "Ops. Ocorreu algum erro. Tente cancelar o pedido novamente."
		end
	end

	def restaurante #edita informações do restaurante, as mesmas da hora de criar
		@cozinhas = Cozinha.all
	end

	private

	def sabor_params
		params.require(:sabores_de_pizza)
		.permit(:nome, :descricao, :precoP, :precoM, :precoG, :precoGG, :restaurante_id)
	end

	def get_usuario
		@usuario = current_user
	end

	def get_restaurante
		@restaurante = current_user.restaurante
	end

	def get_pedidos
		@pedidos = Pedido.includes(:item_pedidos, :itens, :usuario).where("restaurante_id = ? AND status > ? ", @restaurante.id, 2).order(:status).order(send_at: :desc)
	end

	def get_qtde_pedidos_abertos
		@qtde_pedidos_abertos = @pedidos.where("status = 3").count
	end
end

app/views/painel/_acoes_de_pedido.html.erb
<% if (@pedido.status < 4) then #exibe o botao de notificacao de entrega somente e se somente o status for menor que 4. Status 4 = pedido saiu para entrega. Status 5 = pedido encerrado sem entrega ao cliente %>
<div class="col-md-12"><p>Clique abaixo para notificar o usuário de que seu pedido saiu para entrega.</p></div>


<div class="col-md-12 encerrar-button">
   <%= button_to painel_pedidos_path, params: { pedido_id: @pedido.id }, class: "btn btn-success" do %>
   <span class="glyphicon glyphicon-ok-sign"></span> Notificar saida para entrega
   <% end %>

</div><!-- COL MD 12 -->

<div class="col-md-12"><p>Clique abaixo para cancelar o pedido SEM ENTREGA ao cliente. O cliente será notificado por email. Mesmo assim, <strong>é altamente recomendável que o cliente seja contatado antes dessa ação.</strong></p></div>

<div class="col-md-12 encerrar-button">
   <%= button_to painel_cancelar_pedido_path, params: { pedido_id: @pedido.id }, class: "btn btn-danger btn-xs" do %>
   <span class="glyphicon glyphicon-ok-sign"></span> Cancelar pedido
   <% end %>

</div><!-- COL MD 12 -->

<% end %>

app/views/painel/_footer.html.erb
	</div><!-- /conteudo -->

</div> <!-- row -->

app/views/painel/_head.html.erb
<% content_for :title do %> Painel Administrativo | <%= @restaurante.nome %> | Comidelivery.com <% end %>

<% flash.each do |name, msg| -%>
	<%= content_tag :div, msg, class: "alert alert-success" %>
<% end -%>

<div class="row">
	<div class="col-md-12 painel-head"><!-- Painel -->

		<img class="show-restaurante-img" src="<%= @restaurante.imagem.url %>">

		<h2><%= @restaurante.nome%> <small> | <span class="glyphicon glyphicon-dashboard"></span> Painel Administrativo</small></h2>

      <% if (@restaurante.status != 'ATIVO' ) then %>
         <div class="alert alert-warning" role="alert">
   			<strong>Atenção!</strong> Seu restaurante ainda não está ativo. Entre em contato para saber como ativá-lo. (contato@comidelivery.com)
   		</div>
         <%end %>
		<div class="panel panel-default">
			<div class="panel-body">
			Página do restaurante: <a href="/restaurantes/<%= @restaurante.id %>-<%= @restaurante.nome.parameterize%>">www.comidelivery.com/restaurantes/<%= @restaurante.id %>-<%= @restaurante.nome.parameterize%></a>
			</div>
		</div>



	</div> <!-- Painel -->
</div><!-- / row titulo -->
<div class="row">

	<%= render 'menu' %>

	<div class="col-md-9 painel-content"><!-- Conteudo-->

app/views/painel/_menu.html.erb
<div class="col-md-2 painel-menu"> <!-- Menu do Painel-->
		<div class="list-group">


		<a class="list-group-item" href="/painel/pedidos">Pedidos<span class="badge"><%= @qtde_pedidos_abertos %></span></a></li>

		 <a class="list-group-item" href="/painel/produtos">Produtos</a>
		 <!--<a class="list-group-item" href="/painel/pizzas">Pizzas</a>-->
		 <a class="list-group-item" href="/painel/restaurante">Editar Restaurante</a>
		</div>
</div><!-- /menu -->

app/views/painel/_sabor_form.html.erb
<%= form_for @sabor, url: 'new', html: {class: "form-horizontal", role: "form"} do |f|%>
  <% if @sabor.errors.any? %>
    <div id="error_explanation">
      <h2><%= I18n.t('item.new.error_msg') %></h2>

      <ul>
      <% @sabor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">

        <%= f.label :nome, 'Nome', class: "col-md-12" %>
        
        <div class="col-md-4">
          <%= f.text_field :nome, class: 'form-control', placeholder: 'Exemplo: Calabresa' %>
        </div>
        
  </div>

  <div class="form-group">

        <%= f.label :descricao, 'Descrição', class: "col-md-12" %>
        
        <div class="col-md-4">
          <%= f.text_area :descricao, class: 'form-control', placeholder: 'Descreva os ingredientes' %>
        </div>
        
  </div>

  <div class="form-group">

        <%= f.label :precoP, 'Preço P', class: "col-md-12" %>
        <span id="helpBlock" class="col-md-12 help-block">Preço em centavos. Não use vírgula. Os dois últimos dígitos são os centavos. Exemplo: para R$ 10,50 - Digite 1050</span>
        
        <div class="col-md-4">
          <%= f.number_field :precoP, class: 'form-control', placeholder: 'Digite apenas números sem vírgula, os dois últimos digitos são os centavos' %>
        </div>
        
  </div>
  <div class="form-group">

        <%= f.label :precoM, 'Preço M', class: "col-md-12" %>
        
        
        <div class="col-md-4">
          <%= f.number_field :precoM, class: 'form-control', placeholder: 'Digite apenas números sem vírgula, os dois últimos digitos são os centavos' %>
        </div>
        
  </div>
  <div class="form-group">

        <%= f.label :precoG, 'Preço G', class: "col-md-12" %>
        
        
        <div class="col-md-4">
          <%= f.number_field :precoG, class: 'form-control', placeholder: 'Digite apenas números sem vírgula, os dois últimos digitos são os centavos' %>
        </div>
        
  </div>
  <div class="form-group">

        <%= f.label :precoGG, 'Preço GG', class: "col-md-12" %>
        
        <div class="col-md-4">
          <%= f.number_field :precoGG, class: 'form-control', placeholder: 'Digite apenas números sem vírgula, os dois últimos digitos são os centavos' %>
        </div>
        
  </div>
  
  
  <div class="form-group">
    
    <div class="col-sm-8">

     <%= submit_tag "Salvar sabor", class: "btn btn-success btn-lg btn-block" %>

     </div>

  </div>
<% end %>

app/views/painel/_update_sabor_form.html.erb
<%= form_for @sabor, url: "update/#{@sabor.id}", html: {class: "form-horizontal", role: "form"} do |f|%>
  <% if @sabor.errors.any? %>
    <div id="error_explanation">
      <h2><%= I18n.t('item.new.error_msg') %></h2>

      <ul>
      <% @sabor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">

        <%= f.label :nome, 'Nome', class: "col-md-12" %>
        
        <div class="col-md-4">
          <%= f.text_field :nome, class: 'form-control', placeholder: 'Exemplo: Calabresa' %>
        </div>
        
  </div>

  <div class="form-group">

        <%= f.label :descricao, 'Descrição', class: "col-md-12" %>
        
        <div class="col-md-4">
          <%= f.text_area :descricao, class: 'form-control', placeholder: 'Descreva os ingredientes' %>
        </div>
        
  </div>

  <div class="form-group">

        <%= f.label :precoP, 'Preço P', class: "col-md-12" %>
        <span id="helpBlock" class="col-md-12 help-block">Preço em centavos. Não use vírgula. Os dois últimos dígitos são os centavos. Exemplo: para R$ 10,50 - Digite 1050</span>
        
        <div class="col-md-4">
          <%= f.number_field :precoP, class: 'form-control', placeholder: 'Digite apenas números sem vírgula, os dois últimos digitos são os centavos' %>
        </div>
        
  </div>
  <div class="form-group">

        <%= f.label :precoM, 'Preço M', class: "col-md-12" %>
        
        
        <div class="col-md-4">
          <%= f.number_field :precoM, class: 'form-control', placeholder: 'Digite apenas números sem vírgula, os dois últimos digitos são os centavos' %>
        </div>
        
  </div>
  <div class="form-group">

        <%= f.label :precoG, 'Preço G', class: "col-md-12" %>
        
        
        <div class="col-md-4">
          <%= f.number_field :precoG, class: 'form-control', placeholder: 'Digite apenas números sem vírgula, os dois últimos digitos são os centavos' %>
        </div>
        
  </div>
  <div class="form-group">

        <%= f.label :precoGG, 'Preço GG', class: "col-md-12" %>
        
        <div class="col-md-4">
          <%= f.number_field :precoGG, class: 'form-control', placeholder: 'Digite apenas números sem vírgula, os dois últimos digitos são os centavos' %>
        </div>
        
  </div>

  <%= f.hidden_field(:id)%>
  
  
  <div class="form-group">
    
    <div class="col-sm-8">

     <%= submit_tag "Salvar sabor", class: "btn btn-success btn-lg btn-block" %>

     </div>

  </div>
<% end %>

app/views/painel/edit_sabor.html.erb
<%= render 'head' %>
<h2>Editar sabor de pizza</h2>
<p>Você pode editar a descrição e respectivos preços para os diversos tamanhos disponíveis.</p>

<%= render 'update_sabor_form' %>

<%= render 'footer' %>

app/views/painel/index.html.erb
<%= render 'head' %>
<%= render 'footer' %>

app/views/painel/new_sabor.html.erb
<%= render 'head' %>
<h2>Novo sabor de pizza</h2>
<p>Crie um novo sabor com descrição e respectivos preços para os diversos tamanhos disponíveis.</p>

<%= render 'sabor_form' %>

<%= render 'footer' %>

app/views/painel/pedidos.html.erb
<%= render 'head' %>

<div class="row">
<div class="col-md-10">

<h3 style="display:inline">Pedidos Recebidos</h3>

<a href="/painel/pedidos" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-refresh"></span> Atualizar </a>

</div>

</div>




<% unless @pedidos %>
	<p>Sem pedidos ainda.</p>
	<%end%>

<div class="row">
<div class="col-md-12">


<table class="table table-striped pedidos">
	<tr>
		<th>Detalhar</th>
		<th>Identificador</th>
		<th>Status</th>
	    <th>Itens</th>
	    <th>Tempo</th>
	    <th>Preço</th>


	</tr>

	<% @pedidos.each do |pedido| %>
	<tr>
		<td><a href="/painel/pedidos/<%= pedido.id %>" class="btn btn-xs btn-default">Detalhes</a></td>
		<td><%= pedido.id %></td>

		<% if pedido.status == 4 %>
		<td><span class="label label-default">Fechado</span></td>
      <% elsif pedido.status == 5 %>
		<td><span class="label label-default">Cancelado</span></td>
		<% else %>
		<td><span class="label label-success"><strong>Aberto</strong></span></td>
		<% end %>

		<td>
			<ul>
			<% pedido.item_pedidos.each do |itempedido| %>
			<li><%= itempedido.quantidade%> x <%= itempedido.item.nome%></li>
			<% end %>
			</ul>
		</td>

		<td>
			<%=	tempo_de_espera(pedido.send_at.to_i)	%></td>

		<td><%= currency_symbol %> <%= centavos_em_real(pedido.preco_total) %></td>




	</tr>
	<% end %>
</table>

<% unless @pedidos %>

<p>Nenhum pedido em aberto.</p>

<% end %>


</div><!-- row -->
</div><!-- col md 12 -->


<%= render 'footer' %>

app/views/painel/pizzas.html.erb
<%= render 'head' %>

<h2>Sabores de pizza</h2>

<%= link_to 'Cadastrar sabor de pizza', 'pizzas/new', class: "btn btn-success" %>
<p></p>

<% if not @sabores %>
<p>Nenhuma pizza ainda.</p>
<% end %>

<table class="table table-striped">

<tr>
	<th>Nome</th>
    <th>Descrição</th>
    <th>Preço P</th>
    <th>Preço M</th>
    <th>Preço G</th>
    <th>Preço GG</th>
    <th>Editar</th>
    <th>Excluir</th>
</tr>

<% @sabores.each do |p| %>

<tr>
	<td><%= p.nome %></td>

	<td><%= p.descricao %></td>

	<td>R$ <%= centavos_em_real(p.precoP) %></td>

	<td>R$ <%= centavos_em_real(p.precoM) %></td>

	<td>R$ <%= centavos_em_real(p.precoG) %></td>

	<td>R$ <%= centavos_em_real(p.precoGG) %></td>

	<td><%= link_to 'Editar', "edit_sabor/#{p.id}", class: "btn btn-default btn-xs" %></td>

	<td><%= button_to "Excluir", { action: "destroy_sabor", id: p.id },
                                method: :post, data: { confirm: "Confirma exclusão da pizza?" },class: "btn btn-default btn-xs" %></td>

	


</tr>

<% end %>

</table>

<%= render 'footer' %>

app/views/painel/produtos.html.erb
<%= render 'head' %>

<h2>Produtos</h2>

<%= link_to 'Cadastrar produto', new_item_path, class: "btn btn-success" %>
<p></p>

<% if not @produtos %>
<p>Nenhum produto ainda.</p>
<% end %>

<table class="table table-striped">

<tr>
	<th>Categoria</th>
    <th>Nome</th>
    <th>Descrição</th>
    <th>Preço</th>
    <th>Editar</th>
    <th>Excluir</th>
</tr>

<% @produtos.each do |produto| %>

<tr>
	<td><%= produto.categoria.nome %></td>

	<td><%= produto.nome %></td>
	
	<td><%= produto.descricao %></td>

	<td>R$ <%= centavos_em_real(produto.preco_centavos) %></td>

	<td><%= link_to 'Editar', edit_item_path(produto), class: "btn btn-default btn-xs" %></td>

	<td><%= button_to 'Excluir', produto, method: :delete, class: 'btn btn-default btn-xs' %></td>


</tr>

<% end %>

</table>

<%= render 'footer' %>

app/views/painel/restaurante.html.erb
<%= render 'head' %>
<div class="row">
	<div class="col-md-6">
<%= render 'restaurantes/form' %>
</div><!-- col -->
</div><!-- row -->
<%= render 'footer' %>

<!-- Pretty DRY, huh? ;P -->

app/views/painel/show_pedido.html.erb
<%= render 'head' %>

<h3>Detalhes do pedido</h3>


<div class="row">
	<div class="col-md-10">


<ul class="list-group">
	<li class="list-group-item"><strong>Identificador: </strong> <%= @pedido.id %></li>
	<li class="list-group-item"><strong>Hora: </strong> <%= @pedido.updated_at %></li>
	<li class="list-group-item"><strong>Valor: </strong> R$ <%= centavos_em_real(@pedido.preco_total) %></li>
	<li class="list-group-item"><strong>Itens: </strong>
		<ul class="list-group">
		<% @pedido.item_pedidos.each do |itemp| %>
		<li class="list-group-item"><%= itemp.quantidade%> x <%= itemp.item.nome %></li>
		<% end %>


		</ul>

	</li>
	<li class="list-group-item"> <strong>Comentário: </strong>"<%= @pedido.try(:comentario) %>"</li>
	<li class="list-group-item"><strong>Cliente: </strong><%= @pedido.usuario.nome %> <%= @pedido.usuario.sobrenome %> </li>
	<li class="list-group-item"><strong> Telefone: </strong><%= @pedido.usuario.telefone %></li>
	<li class="list-group-item"><strong>Endereço de entrega: </strong>
		<ul class="list-group">
		<li class="list-group-item"><strong>Logradouro: </strong><%= @pedido.endereco.logradouro %></li>
		<li class="list-group-item"><strong>Endereço: </strong><%= @pedido.endereco.endereco %></li>
		<li class="list-group-item"><strong>Numero: </strong><%= @pedido.endereco.numero %></li>
		<li class="list-group-item"><strong>Ponto de referência: </strong><%= @pedido.endereco.ponto_referencia %></li>
		<li class="list-group-item"><strong>CEP: </strong><%= @pedido.endereco.cep %></li>
		<li class="list-group-item"><strong>Cidade: </strong><%= @pedido.endereco.cidade %> / <%= @pedido.endereco.estado %></li>
	</li>
</ul>

</table>

</div>
</div>

<div class="row">

   <%= render "acoes_de_pedido" %>

</div> <!-- ROW -->

<%= render 'footer' %>