config/routes.rb
Rails.application.routes.draw do

  resources :item_pedidos
  resources :usuarios, only: [:new, :create]
  resources :restaurantes
  resource :confirmation, only: [:show]
  resource :user_sessions, only: [:create, :new, :destroy]
  get '/login' => 'user_sessions#new'
  get '/entrar' => 'user_sessions#new'
  get '/pedidos/checkout' => 'pedidos#checkout' # quando o cliente clica em finalizar, na tela do restaurante
  get '/pedidos/acompanhamento' => 'pedidos#acompanhamento'
  resources :pedidos, only: [:create, :new, :destroy, :show, :update]
  get '/account' => 'account#index'

  get '/painel' => 'painel#index'
  get '/painel/pedidos' => 'painel#pedidos'
  get 'painel/pedidos/:id' => 'painel#show_pedido'
  post '/painel/pedidos/' => 'painel#encerrar_pedido'
  post '/painel/cancelar_pedido/' => 'painel#cancelar_pedido'
  get '/painel/produtos' => 'painel#produtos'
  get '/painel/produtos/new' => 'itens#new'
  get '/painel/restaurante' => 'painel#restaurante'
  get 'painel/pizzas' => 'painel#pizzas'
  get 'painel/pizzas/new' => 'painel#new_sabor'
  get 'painel/edit_sabor/:id' => 'painel#edit_sabor'
  post 'painel/pizzas/new' => 'painel#create_sabor'
  patch 'painel/edit_sabor/update/:id' => 'painel#update_sabor'
  post 'painel/pizzas/:id' => 'painel#destroy_sabor'

  resources :enderecos, only: [:create, :new, :destroy]
  resources :itens
  get '/contato' => 'home#suporte'
  get '/cadastro_restaurante' => 'home#cadastro_restaurante'
  get 'precadastro' => 'home#cadastro_restaurante'
  post '/cadastro_restaurante' => 'home#precadastro'
  get 'cadastro_restaurante/sucesso' => 'home#precadastro_sucesso'

  get 'dashboard' => 'dashboard#index'
  get 'dashboard/pedidos' => 'dashboard#pedidos'
  get 'dashboard/pedidos/:id' => 'dashboard#show_pedido'
  get 'dashboard/precadastro' => 'dashboard#precadastro'
  get 'dashboard/edit/:id' => 'dashboard#edit'
  post 'dashboard/update/:id'=> 'dashboard#update'
  patch 'dashboard/update/:id'=> 'dashboard#update'

  get '/busca_restaurantes' => 'restaurantes#busca'

  root 'home#index'

end

app/models/user_session.rb
class UserSession
	include ActiveModel::Model

	attr_accessor :email, :password
	validates_presence_of :email, :password

	def initialize(session, attributes={})
		@session = session
		@email = attributes[:email]
		@password = attributes[:password]
	end

	def authenticate!
		usuario = Usuario.authenticate(@email, @password)
		if usuario.present?
			store(usuario)
		else
			errors.add(:base, :invalid_login)
			false
		end
	end
	
	def store(usuario)
		@session[:user_id] = usuario.id
	end

	def current_user
		Usuario.find(@session[:user_id])
	end

	def user_signed_in?
		@session[:user_id].present?		
	end

	def destroy
		@session[:user_id] = nil
	end

	def restaurante_do_usuario
		current_user.restaurante		
	end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
	before_action :require_no_authentication, only: [:new, :create]
	before_action :require_authentication, only: [:destroy]
	def new
		@user_session = UserSession.new(session)
		@back_to = params[:back_to]
		
	end
	def create
		@user_session = UserSession.new(session, params[:user_session])
		if @user_session.authenticate!
			
			redirect_back_or_default(root_path)

		else
			render :new
		end
	end

	def destroy
		user_session.destroy
		redirect_to root_path, notice: t('flash.notice.signed_out')		
	end

	private

	def redirect_back_or_default(default)
    	redirect_to(session[:return_to] || default)
    	session[:return_to] = nil
	end
	
end

app/views/user_sessions/new.html.erb
<% content_for :title do %>Entrar | Comidelivery.com <% end %>
<div class="row">
	<div class="col-md-4">
		<div class="page-header">
			<h1><%= t ".title" %></h1>
		</div>
		<p><%= @back_to %></p>

		<% flash.each do |name, msg| -%>
	      <%= content_tag :div, msg, class: "alert alert-success" %>
	    <% end -%>

		<% if @user_session.errors.has_key? :base %>
			<div class="alert alert-danger" role="alert">
				<%= @user_session.errors[:base].join(', ') %>
			</div>
		<% end %>

		<%= form_for @user_session, html: {class: "form-horizontal", role: "form"} do |f|%>
			<div class="form-group">

				<%= f.label :email, t('.email'), class: "col-sm-2 control-label" %>
				<div class="col-sm-10">
					<%= f.email_field :email, class: 'form-control', placeholder: "Digite seu email" %>
				</div>
				
			</div>
			
			    
			   
			
			<div class="form-group">
				<%= f.label :password, t('.password'),class: "col-sm-2 control-label" %>
				<div class="col-sm-10">
					<%= f.password_field :password, class: 'form-control', placeholder: "Digite sua senha" %>
				</div>
			</div>

			<% if @back_to %>
			<input type="hidden" name="back_to" value="<%= @back_to %>">
			<% end %>
				
			
			<div class="form-group">

				<div class="col-sm-2"></div>
				<div class="col-sm-8">

					<%= f.button t('.submit'), class: 'btn btn-primary' %>
			    	
			    </div>
			</div>

		<%end%>
		

			<p><%= I18n.t(".user_sessions.new.no_account") %> <%= link_to t('.sign_up'), new_usuario_path, class: "btn  btn-default btn-sm" %></p>

			<p>Esqueceu sua senha? Entre em <a href="/contato">contato</a> com nosso suporte.</p>

					
			    	
			 
		

	</div>
</div><!-- row -->